### ISSUE TITLE
Could you please change the name of this project?

### ISSUE THREAD

**Issue by mikemaccana** [CoSchedule/npm-agave#1]
[agave.js](http://agavejs.org) project has been using the name `agave` in the JavaScript world for a couple of years now. When choosing the name, we deliberately picked something that wasn't already taken, as a result we have:
 - the [agavejs.org domain name](http://agavejs.org)
 - the [npm package name](https://www.npmjs.com/package/agave) - [per the npm guidelines, without the 'js' suffix](https://docs.npmjs.com/files/package.json)
 - the [agavejs twitter account](https://twitter.com/agavejs)
 - the [top entry on Google for 'agave.js'](https://github.com/mikemaccana/agave). 

A lot of time and energy has been spent writing the project and promoting it under the name agavejs - to avoid confusion, could you please change the name of your project? This would also help your own project to be more easily found.

**Comment by Cosrnos** [comment]
@mikemaccana Terribly sorry for the delay in a response here! I'd be happy to deprecate the npm-agave package and rename the project!

Thanks for reaching out to us!

**Comment by Cosrnos** [comment]
@mikemaccana We've deprecated the npm agavejs module and updated our readme to link to both our new project as well as the agavejs.org domain name. Sorry again for the naming issue!

**Comment by mikemaccana** [comment]
Thanks guys! We really appreciate it.
